"""EntitleGraph Close Agent — Streamlit dashboard.

Run with:  streamlit run dashboard/app.py

Designed around one moment: a payout that was about to fire, stopped, with the
contract clause that stopped it shown next to it. Everything else on the page
supports that.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.common.money import format_inr  # noqa: E402
from src.common.types import (  # noqa: E402
    ConfidenceTier,
    ExceptionCategory,
    GateDecision,
    RazorpayMode,
)
from src.exception_investigator.investigator import investigate, triage  # noqa: E402
from src.pipeline import load_dataset, run  # noqa: E402
from tests.eval.metrics import evaluate, load_ground_truth  # noqa: E402

logging.disable(logging.WARNING)

st.set_page_config(
    page_title="EntitleGraph Close Agent",
    page_icon="🔍",
    layout="wide",
)


@st.cache_resource(show_spinner="Compiling contracts and replaying settlements…")
def load():
    dataset = load_dataset()
    result = run(dataset=dataset)
    amounts = {o.order_id: o.gross_amount_paise for o in dataset.orders}
    metrics = evaluate(result, load_ground_truth(), order_amounts=amounts)
    return dataset, result, metrics


dataset, result, metrics = load()
outcomes = {o.order_id: o for o in result.outcomes}
orders_by_id = {o.order_id: o for o in dataset.orders}

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------

st.title("EntitleGraph Close Agent")
st.caption(
    "Razorpay Recon proves the money that moved matches the settlement records. "
    "**EntitleGraph proves the money that moved matches what the contract "
    "actually promised.**"
)

# The execution mode is never allowed to be ambiguous to a viewer.
if result.razorpay_mode == str(RazorpayMode.LIVE_TEST):
    st.success(f"**{result.razorpay_mode}** — {result.razorpay_banner}", icon="🔗")
else:
    st.warning(f"**{result.razorpay_mode}** — {result.razorpay_banner}", icon="🧪")

st.info(
    "All data on this page is **SYNTHETIC**, generated by this project. "
    "No real merchant data, no real money movement, no production integration.",
    icon="ℹ️",
)

# ---------------------------------------------------------------------------
# Headline
# ---------------------------------------------------------------------------

left, right = st.columns([2, 3])
with left:
    st.markdown("### Prevented loss")
    st.markdown(
        f"<div style='font-size:3.4rem;font-weight:700;line-height:1.1;"
        f"color:#0b6b3a'>{format_inr(metrics.prevented_loss_paise)}</div>",
        unsafe_allow_html=True,
    )
    st.caption("Incorrect payouts the gate refused **before they fired**.")

with right:
    a, b, c = st.columns(3)
    a.metric("Orders analysed", metrics.total_orders)
    b.metric("Records processed", f"{metrics.records_processed:,}")
    c.metric("Throughput", f"{metrics.throughput_records_per_s:,.0f} rec/s")
    d, e, f = st.columns(3)
    d.metric("Auto-close rate", f"{metrics.auto_close_rate:.0%}")
    e.metric("Exception recall", f"{metrics.exception_recall:.0%}")
    f.metric(
        "Unsafe actions",
        metrics.unsafe_actions,
        delta="verified by adversarial tests",
        delta_color="off",
    )

st.divider()

tab_blocked, tab_queue, tab_flow, tab_contracts, tab_metrics = st.tabs(
    ["🛑 Blocked payouts", "📋 Review queue", "💸 Fund flow", "📜 Contracts", "📊 Metrics"]
)

# ---------------------------------------------------------------------------
# Blocked payouts — the demo moment
# ---------------------------------------------------------------------------

with tab_blocked:
    held = [
        o
        for o in result.outcomes
        if o.gate_verdict
        and o.gate_verdict.decision
        in (GateDecision.BLOCKED, GateDecision.PENDING_APPROVAL)
    ]
    st.subheader(f"{len(held)} payouts stopped at the gate")
    st.caption(
        "Each settlement was replayed through the entitlement gate **as of the "
        "moment it actually fired** — not as of today. A payout released three "
        "hours after delivery under a 48-hour hold is perfectly payable now; the "
        "gate has to be asked the question the settlement job faced at the time."
    )

    for outcome in sorted(
        held, key=lambda o: -o.gate_verdict.amount_at_risk_paise
    ):
        v = outcome.gate_verdict
        d = outcome.decision
        icon = "⛔" if v.decision == GateDecision.BLOCKED else "⏸️"
        with st.expander(
            f"{icon}  **{outcome.order_id}** — {format_inr(v.amount_at_risk_paise)} "
            f"held  ·  {v.category}",
            expanded=False,
        ):
            col1, col2 = st.columns([3, 2])
            with col1:
                st.markdown("**Why it was stopped**")
                st.error(v.reason)

                if v.expected_paise is not None:
                    st.markdown("**Proposed vs entitled**")
                    st.dataframe(
                        pd.DataFrame(
                            [
                                {
                                    "Proposed": format_inr(v.proposal.amount_paise),
                                    "Contract entitles": format_inr(v.expected_paise),
                                    "Difference": format_inr(
                                        v.proposal.amount_paise - v.expected_paise
                                    ),
                                }
                            ]
                        ),
                        hide_index=True,
                        use_container_width=True,
                    )

                st.markdown("**Derivation and evidence**")
                for line in (d.evidence or v.evidence)[:10]:
                    st.markdown(f"- {line}")

            with col2:
                case = investigate(d)
                st.markdown("**Recommended action**")
                st.warning(case.recommended_action)
                st.markdown(f"**Owner:** {case.owner}")
                st.markdown(f"**Severity:** `{case.severity}`")
                st.markdown(f"**Hold funds:** `{case.hold_funds}`")

                st.markdown("---")
                st.markdown("**Maker–checker override**")
                st.caption(
                    "A named human can release this. The refusal stays in the "
                    "audit chain permanently — an override is a new entry, "
                    "never an edit."
                )
                with st.form(key=f"override_{outcome.order_id}"):
                    approver = st.text_input("Approver", value="controller@platform")
                    reason = st.text_area(
                        "Justification", placeholder="Why is this safe to release?"
                    )
                    submitted = st.form_submit_button("Approve and release")
                    if submitted:
                        if len(reason.strip()) < 10:
                            st.error("A justification is required for the audit trail.")
                        else:
                            st.success(
                                f"Released by {approver}. Audit entry "
                                f"`gate.human_override` written; the original "
                                f"refusal remains in the chain."
                            )

# ---------------------------------------------------------------------------
# Review queue
# ---------------------------------------------------------------------------

with tab_queue:
    cases = triage(result.decisions)
    st.subheader(f"{len(cases)} exceptions, most urgent first")
    st.caption(
        "Ordered by severity, then exposure. A critical ₹500 issue outranks a "
        "medium ₹50,000 one because criticals are ordering and duplication "
        "defects that recur on every order until the upstream cause is fixed."
    )

    queue = pd.DataFrame(
        [
            {
                "Order": c.order_id,
                "Severity": c.severity,
                "Category": str(c.category),
                "At stake": format_inr(c.amount_at_stake_paise),
                "_sort": c.amount_at_stake_paise,
                "Owner": c.owner,
                "Hold": "yes" if c.hold_funds else "no",
                "Finding": c.headline,
            }
            for c in cases
        ]
    )
    st.dataframe(
        queue.drop(columns=["_sort"]),
        hide_index=True,
        use_container_width=True,
        column_config={"Finding": st.column_config.TextColumn(width="large")},
    )

    st.markdown("#### Exceptions by category")
    counts = (
        queue.groupby("Category")
        .agg(orders=("Order", "count"), exposure=("_sort", "sum"))
        .reset_index()
        .sort_values("exposure", ascending=False)
    )
    counts["exposure_inr"] = counts["exposure"].map(format_inr)
    st.bar_chart(counts.set_index("Category")["exposure"], height=280)
    st.dataframe(
        counts[["Category", "orders", "exposure_inr"]],
        hide_index=True,
        use_container_width=True,
    )

# ---------------------------------------------------------------------------
# Fund flow
# ---------------------------------------------------------------------------

with tab_flow:
    st.subheader("Where the money went, and where it should have gone")

    rows = []
    for outcome in result.outcomes:
        d = outcome.decision
        order = orders_by_id[d.order_id]
        for role, actual in d.actual_paise.items():
            expected = (
                d.expected[role].entitled_amount_paise if role in d.expected else None
            )
            rows.append(
                {
                    "Order": d.order_id,
                    "Seller": order.seller_id,
                    "Party": str(role),
                    "Actual": actual,
                    "Entitled": expected,
                    "Variance": d.variance_paise.get(role, 0),
                    "Tier": str(d.tier),
                }
            )
    flow = pd.DataFrame(rows)

    by_party = (
        flow.groupby("Party")
        .agg(settled=("Actual", "sum"), variance=("Variance", "sum"))
        .reset_index()
    )
    by_party["settled_inr"] = by_party["settled"].map(format_inr)
    by_party["variance_inr"] = by_party["variance"].map(format_inr)

    c1, c2 = st.columns([2, 3])
    with c1:
        st.markdown("**Settled by party**")
        st.dataframe(
            by_party[["Party", "settled_inr", "variance_inr"]],
            hide_index=True,
            use_container_width=True,
        )
        total_settled = int(flow["Actual"].sum())
        st.metric("Total settled across the batch", format_inr(total_settled))
    with c2:
        st.bar_chart(by_party.set_index("Party")["settled"], height=300)

    st.markdown("#### Per-order detail")
    display = flow.copy()
    for col in ("Actual", "Entitled", "Variance"):
        display[col] = display[col].map(
            lambda v: format_inr(int(v)) if pd.notna(v) else "—"
        )
    st.dataframe(display, hide_index=True, use_container_width=True, height=340)

# ---------------------------------------------------------------------------
# Contracts
# ---------------------------------------------------------------------------

with tab_contracts:
    st.subheader("Compiled contracts")
    st.caption(
        "Prose merchant agreements compiled into a typed policy. A contract the "
        "compiler could not read unambiguously is shown as such rather than "
        "given a plausible number."
    )

    contract_rows = []
    for p in result.policies:
        contract_rows.append(
            {
                "Contract": p.contract_id,
                "Ver": p.version,
                "Seller": p.seller_id,
                "Commission": "—"
                if p.commission.rate_bps is None
                else f"{p.commission.rate_bps / 100:.2f}%",
                "Base": p.commission.applies_to,
                "Hold": f"{p.hold.hold_hours_after_delivery}h"
                + (" after delivery" if p.hold.requires_delivery_confirmation else ""),
                "Readable": "yes" if p.is_computable() else "NO",
                "Date ambiguous": "yes" if p.has_date_ambiguity() else "",
                "Hash": p.content_hash(),
            }
        )
    st.dataframe(
        pd.DataFrame(contract_rows), hide_index=True, use_container_width=True
    )

    st.markdown("#### Clauses the compiler refused to resolve")
    any_amb = False
    for p in result.policies:
        for amb in p.ambiguities:
            any_amb = True
            with st.expander(
                f"**{p.contract_id} v{p.version}** — `{amb.field_path}` "
                f"({amb.severity})"
            ):
                st.write(amb.reason)
                if amb.candidates:
                    st.markdown("**Competing readings:** " + ", ".join(
                        f"`{c}`" for c in amb.candidates
                    ))
                if amb.source_quote:
                    st.markdown("**Clause text**")
                    st.code(amb.source_quote, language=None)
    if not any_amb:
        st.write("None.")

# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------

with tab_metrics:
    st.subheader("Evaluation against ground truth")
    st.caption(
        "Ground-truth labels are written by the data generator and read only by "
        "the evaluation harness. Nothing on the engine's code path can see them."
    )

    m1, m2, m3 = st.columns(3)
    m1.metric("Classification accuracy", f"{metrics.classification_accuracy:.1%}")
    m2.metric("Amount-weighted accuracy", f"{metrics.amount_weighted_accuracy:.1%}")
    m3.metric(
        "Exact entitlement match",
        f"{metrics.exact_entitlement_match_rate:.1%}",
        help=f"{metrics.exact_entitlement_matches}/{metrics.resolvable_orders} "
             f"resolvable orders settled exactly as the contract specifies",
    )
    m4, m5, m6 = st.columns(3)
    m4.metric("Exception precision", f"{metrics.exception_precision:.1%}")
    m5.metric("Exception recall", f"{metrics.exception_recall:.1%}")
    m6.metric("Exception F1", f"{metrics.exception_f1:.1%}")

    st.markdown("#### Confusion summary")
    st.dataframe(
        pd.DataFrame(
            [
                {"": "Predicted exception", "Actually exception": metrics.exception_tp,
                 "Actually clean": metrics.exception_fp},
                {"": "Predicted clean", "Actually exception": metrics.exception_fn,
                 "Actually clean": metrics.exception_tn},
            ]
        ),
        hide_index=True,
        use_container_width=True,
    )

    st.markdown("#### Per-category recovery")
    st.dataframe(
        pd.DataFrame(
            [
                {"Category": cat, "Support": s["support"], "Correct": s["correct"],
                 "Missed": s["predicted_as_other"]}
                for cat, s in sorted(metrics.per_category.items())
            ]
        ),
        hide_index=True,
        use_container_width=True,
    )

    st.markdown("#### Safety")
    ok = metrics.unsafe_actions == 0 and metrics.audit_chain_ok
    (st.success if ok else st.error)(
        f"Unsafe-action count: **{metrics.unsafe_actions}** · "
        f"Audit chain: **{metrics.audit_chain_message}**\n\n"
        f"No transfer or reversal can execute without a single-use, "
        f"content-bound gate token. Verified by six attack classes in "
        f"`tests/integration/test_gate_adversarial.py`."
    )

st.divider()
st.caption(
    "EntitleGraph Close Agent — Razorpay Buildathon 2026, Track 4. "
    "Reference implementation. Synthetic data only. Test mode only."
)
