"""EntitleGraph Close Agent — Streamlit dashboard.

Run with:  streamlit run dashboard/app.py

Designed around one moment: a payout that was about to fire, stopped, with the
contract clause that stopped it shown next to it. Everything else on the page
supports that.

Visual identity lives in `dashboard/theme.py`. The important surfaces are
rendered as scoped `.eg-*` HTML rather than styled Streamlit widgets, because
CSS that targets Streamlit's generated class names breaks between releases.
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dashboard import theme  # noqa: E402
from src.common.money import format_inr  # noqa: E402
from src.common.types import (  # noqa: E402
    ConfidenceTier,
    ExceptionCategory,
    GateDecision,
    PartyRole,
    RazorpayMode,
)
from src.exception_investigator.investigator import investigate, triage  # noqa: E402
from src.pipeline import load_dataset, run  # noqa: E402
from tests.eval.metrics import evaluate, load_ground_truth  # noqa: E402

logging.disable(logging.WARNING)

st.set_page_config(
    page_title="EntitleGraph Close Agent",
    page_icon="◆",
    layout="wide",
    initial_sidebar_state="collapsed",
)
st.markdown(theme.CSS, unsafe_allow_html=True)


def _html(markup: str) -> None:
    st.markdown(markup, unsafe_allow_html=True)


@st.cache_resource(show_spinner="Compiling contracts and replaying settlements…")
def load():
    dataset = load_dataset()
    result = run(dataset=dataset)
    amounts = {o.order_id: o.gross_amount_paise for o in dataset.orders}
    metrics = evaluate(result, load_ground_truth(), order_amounts=amounts)
    return dataset, result, metrics


dataset, result, metrics = load()
outcomes = {o.order_id: o for o in result.outcomes}
orders_by_id = {o.order_id: o for o in dataset.orders}

# ---------------------------------------------------------------------------
# Masthead + headline
# ---------------------------------------------------------------------------

_html(theme.masthead(mode=result.razorpay_mode, banner=result.razorpay_banner))

_html(
    theme.hero(
        theme.headline(
            format_inr(metrics.prevented_loss_paise),
            label="Prevented loss",
            sub="Incorrect payouts the gate refused before they fired. "
            "Excludes anything a human later released.",
        ),
        theme.kpi_grid(
            [
                theme.kpi(
                    "Orders analysed",
                    f"{metrics.total_orders}",
                    f"{metrics.records_processed:,} linked records",
                    theme.BRAND,
                ),
                theme.kpi(
                    "Auto-close rate",
                    f"{metrics.auto_close_rate:.0%}",
                    f"{metrics.auto_closed} closed with no human",
                    theme.CLEARED,
                ),
                theme.kpi(
                    "Exception recall",
                    f"{metrics.exception_recall:.0%}",
                    "against held-out ground truth",
                    theme.CLEARED,
                ),
                theme.kpi(
                    "Held for review",
                    f"{metrics.total_orders - metrics.auto_closed}",
                    "routed to a named owner",
                    theme.HELD,
                ),
                theme.kpi(
                    "Throughput",
                    f"{metrics.throughput_records_per_s:,.0f}/s",
                    "records per second",
                    theme.INFO,
                ),
                theme.kpi(
                    "Unsafe actions",
                    f"{metrics.unsafe_actions}",
                    "verified by 6 attack classes",
                    theme.CLEARED if metrics.unsafe_actions == 0 else theme.BLOCKED,
                ),
            ]
        ),
    )
)

_html(
    '<p class="eg-lede" style="margin-bottom:20px">'
    "All data on this page is <strong style='color:#F4F3FF'>synthetic</strong>, "
    "generated by this project. No real merchant data, no real money movement, "
    "no production integration."
    "</p>"
)

tab_blocked, tab_queue, tab_flow, tab_contracts, tab_metrics = st.tabs(
    ["Blocked payouts", "Review queue", "Fund flow", "Contracts", "Evaluation"]
)

# ---------------------------------------------------------------------------
# Blocked payouts — the demo moment
# ---------------------------------------------------------------------------

with tab_blocked:
    held = [
        o
        for o in result.outcomes
        if o.gate_verdict
        and o.gate_verdict.decision
        in (GateDecision.BLOCKED, GateDecision.PENDING_APPROVAL)
    ]
    total_held = sum(o.gate_verdict.amount_at_risk_paise for o in held)

    _html(theme.section("Payouts stopped at the gate", f"{len(held)} held"))
    _html(
        theme.lede(
            "Each settlement was replayed through the entitlement gate as of the "
            "moment it actually fired, not as of today. A payout released three "
            "hours after delivery under a 48-hour hold is perfectly payable now; "
            "the gate has to be asked the question the settlement job faced at "
            "the time."
        )
    )
    _html(
        theme.kpi_grid(
            [
                theme.kpi("Total held", format_inr(total_held), "across all refusals", theme.BLOCKED),
                theme.kpi(
                    "Blocked outright",
                    f"{sum(1 for o in held if o.gate_verdict.decision == GateDecision.BLOCKED)}",
                    "contradicts the contract",
                    theme.BLOCKED,
                ),
                theme.kpi(
                    "Pending decision",
                    f"{sum(1 for o in held if o.gate_verdict.decision == GateDecision.PENDING_APPROVAL)}",
                    "contract unreadable",
                    theme.HELD,
                ),
            ]
        )
    )
    st.write("")

    for outcome in sorted(held, key=lambda o: -o.gate_verdict.amount_at_risk_paise):
        v = outcome.gate_verdict
        d = outcome.decision
        colour = theme.state_color(str(v.decision))
        case = investigate(d)

        with st.expander(
            f"{outcome.order_id}   ·   {format_inr(v.amount_at_risk_paise)} held"
            f"   ·   {str(v.category).replace('_', ' ')}",
            expanded=False,
        ):
            left, right = st.columns([3, 2], gap="medium")

            with left:
                _html(
                    f'<div class="eg-kicker">Why it was stopped</div>'
                    f'<div class="eg-reason">{v.reason}</div>'
                )
                if v.expected_paise is not None:
                    delta = v.proposal.amount_paise - v.expected_paise
                    _html(
                        '<div class="eg-kicker" style="margin-top:18px">'
                        "Proposed vs entitled</div>"
                        f'<div class="eg-card"><dl class="eg-kv">'
                        f"<dt>Proposed</dt><dd class='eg-money'>{format_inr(v.proposal.amount_paise)}</dd>"
                        f"<dt>Contract entitles</dt><dd class='eg-money'>{format_inr(v.expected_paise)}</dd>"
                        f"<dt>Difference</dt><dd class='eg-money' style='color:{theme.BLOCKED}'>"
                        f"{format_inr(delta)}</dd></dl></div>"
                    )
                _html(
                    '<div class="eg-kicker" style="margin-top:18px">'
                    "Derivation and evidence</div>"
                )
                _html(theme.evidence(list(d.evidence or v.evidence)[:10]))

            with right:
                _html(
                    f'<div class="eg-kicker">Severity</div>'
                    f"{theme.pill(case.severity, theme.state_color(case.severity))}"
                    f'<div class="eg-kicker" style="margin-top:18px">Recommended action</div>'
                    f'<div class="eg-action">{case.recommended_action}</div>'
                    f'<div class="eg-card" style="margin-top:14px"><dl class="eg-kv">'
                    f"<dt>Owner</dt><dd>{case.owner}</dd>"
                    f"<dt>Hold funds</dt><dd>{'yes' if case.hold_funds else 'no'}</dd>"
                    f"<dt>Contract</dt><dd>{d.contract_id}"
                    f"{f' v{d.contract_version}' if d.contract_version else ''}</dd>"
                    f"</dl></div>"
                )

                _html(
                    '<div class="eg-kicker" style="margin-top:18px">'
                    "Maker–checker override</div>"
                )
                st.caption(
                    "A named human can release this. The refusal stays in the "
                    "audit chain permanently — an override is a new entry, never "
                    "an edit."
                )
                with st.form(key=f"override_{outcome.order_id}"):
                    approver = st.text_input("Approver", value="controller@platform")
                    reason = st.text_area(
                        "Justification", placeholder="Why is this safe to release?"
                    )
                    if st.form_submit_button("Approve and release"):
                        if len(reason.strip()) < 10:
                            st.error("A justification is required for the audit trail.")
                        else:
                            st.success(
                                f"Released by {approver}. Audit entry "
                                "`gate.human_override` written; the original "
                                "refusal remains in the chain."
                            )

# ---------------------------------------------------------------------------
# Review queue
# ---------------------------------------------------------------------------

with tab_queue:
    cases = triage(result.decisions)
    _html(theme.section("Exception review queue", f"{len(cases)} open"))
    _html(
        theme.lede(
            "Ordered by severity, then exposure. A critical ₹500 issue outranks a "
            "medium ₹50,000 one because criticals are ordering and duplication "
            "defects that recur on every order until the upstream cause is fixed."
        )
    )

    by_sev: dict[str, list] = {}
    for c in cases:
        by_sev.setdefault(c.severity, []).append(c)
    _html(
        theme.kpi_grid(
            [
                theme.kpi(
                    sev.title(),
                    f"{len(items)}",
                    format_inr(sum(i.amount_at_stake_paise for i in items)),
                    theme.state_color(sev),
                )
                for sev, items in sorted(
                    by_sev.items(),
                    key=lambda kv: ["critical", "high", "medium", "low", "info"].index(kv[0]),
                )
            ]
        )
    )
    st.write("")

    queue = pd.DataFrame(
        [
            {
                "Order": c.order_id,
                "Severity": c.severity,
                "Category": str(c.category).replace("_", " "),
                "At stake": format_inr(c.amount_at_stake_paise),
                "Owner": c.owner,
                "Hold": "yes" if c.hold_funds else "no",
                "Finding": c.headline,
            }
            for c in cases
        ]
    )
    st.dataframe(
        queue,
        hide_index=True,
        use_container_width=True,
        column_config={"Finding": st.column_config.TextColumn(width="large")},
    )

    _html(theme.section("Exposure by root cause"))
    agg: dict[str, int] = {}
    for c in cases:
        agg[str(c.category).replace("_", " ")] = (
            agg.get(str(c.category).replace("_", " "), 0) + c.amount_at_stake_paise
        )
    peak = max(agg.values()) if agg else 1
    _html(
        theme.bars(
            [
                (name, max(2, round(v * 100 / peak)), format_inr(v), theme.BLOCKED)
                for name, v in sorted(agg.items(), key=lambda kv: -kv[1])
            ]
        )
    )

# ---------------------------------------------------------------------------
# Fund flow
# ---------------------------------------------------------------------------

with tab_flow:
    _html(theme.section("Where the money went, and where it should have gone"))

    rows = []
    for outcome in result.outcomes:
        d = outcome.decision
        order = orders_by_id[d.order_id]
        for role, actual in d.actual_paise.items():
            expected = (
                d.expected[role].entitled_amount_paise if role in d.expected else None
            )
            rows.append(
                {
                    "Order": d.order_id,
                    "Seller": order.seller_id,
                    "Party": str(role).replace("_", " "),
                    "Actual": actual,
                    "Entitled": expected,
                    "Variance": d.variance_paise.get(role, 0),
                    "Tier": str(d.tier).replace("_", " "),
                }
            )
    flow = pd.DataFrame(rows)

    by_party = (
        flow.groupby("Party")
        .agg(settled=("Actual", "sum"), variance=("Variance", "sum"))
        .reset_index()
        .sort_values("settled", ascending=False)
    )
    peak = int(by_party["settled"].max()) or 1

    _html(
        theme.kpi_grid(
            [
                theme.kpi(
                    "Total settled",
                    format_inr(int(flow["Actual"].sum())),
                    "across the batch",
                    theme.BRAND,
                ),
                theme.kpi(
                    "Net variance",
                    format_inr(int(flow["Variance"].sum())),
                    "actual minus payable-now",
                    theme.HELD,
                ),
                theme.kpi(
                    "Parties",
                    f"{by_party.shape[0]}",
                    "seller / platform / delivery",
                    theme.INFO,
                ),
            ]
        )
    )

    _html(theme.section("Settled by party"))
    _html(
        theme.bars(
            [
                (
                    str(r["Party"]),
                    max(2, round(int(r["settled"]) * 100 / peak)),
                    format_inr(int(r["settled"])),
                    theme.CLEARED,
                )
                for _, r in by_party.iterrows()
            ]
        )
    )

    _html(theme.section("Per-order detail"))
    display = flow.copy()
    for col in ("Actual", "Entitled", "Variance"):
        display[col] = display[col].map(
            lambda v: format_inr(int(v)) if pd.notna(v) else "—"
        )
    st.dataframe(display, hide_index=True, use_container_width=True, height=380)

# ---------------------------------------------------------------------------
# Contracts
# ---------------------------------------------------------------------------

with tab_contracts:
    readable = sum(1 for p in result.policies if p.is_computable())
    _html(theme.section("Compiled contracts", f"{len(result.policies)} versions"))
    _html(
        theme.lede(
            "Prose merchant agreements compiled into a typed policy. A contract "
            "the compiler could not read unambiguously is shown as such rather "
            "than given a plausible number."
        )
    )
    _html(
        theme.kpi_grid(
            [
                theme.kpi("Readable", f"{readable}", "yield a defensible figure", theme.CLEARED),
                theme.kpi(
                    "Refused",
                    f"{len(result.policies) - readable}",
                    "terms cannot be determined",
                    theme.BLOCKED,
                ),
                theme.kpi(
                    "Date-ambiguous",
                    f"{sum(1 for p in result.policies if p.has_date_ambiguity())}",
                    "competing effective dates",
                    theme.HELD,
                ),
            ]
        )
    )
    st.write("")

    st.dataframe(
        pd.DataFrame(
            [
                {
                    "Contract": p.contract_id,
                    "Ver": p.version,
                    "Seller": p.seller_id,
                    "Commission": "—"
                    if p.commission.rate_bps is None
                    else f"{p.commission.rate_bps / 100:.2f}%",
                    "Base": p.commission.applies_to.replace("_", " "),
                    "Hold": f"{p.hold.hold_hours_after_delivery}h"
                    + (" post-delivery" if p.hold.requires_delivery_confirmation else ""),
                    "Readable": "yes" if p.is_computable() else "NO",
                    "Date ambiguous": "yes" if p.has_date_ambiguity() else "",
                    "Hash": p.content_hash(),
                }
                for p in result.policies
            ]
        ),
        hide_index=True,
        use_container_width=True,
    )

    _html(theme.section("Clauses the compiler refused to resolve"))
    found = False
    for p in result.policies:
        for amb in p.ambiguities:
            found = True
            with st.expander(
                f"{p.contract_id} v{p.version}   ·   {amb.field_path}   ·   {amb.severity}"
            ):
                _html(f'<p class="eg-lede">{amb.reason}</p>')
                if amb.candidates:
                    _html(
                        '<div class="eg-kicker" style="margin-top:14px">'
                        "Competing readings</div>"
                        + " ".join(
                            theme.pill(c, theme.HELD) for c in amb.candidates
                        )
                    )
                if amb.source_quote:
                    _html(
                        '<div class="eg-kicker" style="margin-top:14px">Clause text</div>'
                        f'<div class="eg-quote">{amb.source_quote}</div>'
                    )
    if not found:
        _html(theme.lede("None."))

# ---------------------------------------------------------------------------
# Evaluation
# ---------------------------------------------------------------------------

with tab_metrics:
    _html(theme.section("Evaluation against ground truth"))
    _html(
        theme.lede(
            "Ground-truth labels are written by the data generator and read only "
            "by the evaluation harness. Nothing on the engine's code path can "
            "see them."
        )
    )
    _html(
        theme.kpi_grid(
            [
                theme.kpi(
                    "Classification",
                    f"{metrics.classification_accuracy:.1%}",
                    "predicted category vs truth",
                    theme.CLEARED,
                ),
                theme.kpi(
                    "Amount-weighted",
                    f"{metrics.amount_weighted_accuracy:.1%}",
                    "weighted by order value",
                    theme.CLEARED,
                ),
                theme.kpi(
                    "Exact entitlement",
                    f"{metrics.exact_entitlement_match_rate:.1%}",
                    f"{metrics.exact_entitlement_matches}/{metrics.resolvable_orders} resolvable",
                    theme.INFO,
                ),
                theme.kpi(
                    "Precision",
                    f"{metrics.exception_precision:.1%}",
                    f"TP {metrics.exception_tp} · FP {metrics.exception_fp}",
                    theme.CLEARED,
                ),
                theme.kpi(
                    "Recall",
                    f"{metrics.exception_recall:.1%}",
                    f"FN {metrics.exception_fn} · TN {metrics.exception_tn}",
                    theme.CLEARED,
                ),
                theme.kpi(
                    "F1",
                    f"{metrics.exception_f1:.1%}",
                    "harmonic mean",
                    theme.CLEARED,
                ),
            ]
        )
    )

    _html(theme.section("Per-category recovery"))
    per_cat = sorted(metrics.per_category.items())
    peak = max((s["support"] for _, s in per_cat), default=1)
    _html(
        theme.bars(
            [
                (
                    cat.replace("_", " "),
                    max(4, round(stats["support"] * 100 / peak)),
                    f"{stats['correct']}/{stats['support']}",
                    theme.CLEARED if stats["correct"] == stats["support"] else theme.HELD,
                )
                for cat, stats in per_cat
            ]
        )
    )

    _html(theme.section("Safety"))
    ok = metrics.unsafe_actions == 0 and metrics.audit_chain_ok
    _html(
        f'<div class="eg-card eg-card--accent" '
        f'style="--eg-accent:{theme.CLEARED if ok else theme.BLOCKED}">'
        f'<dl class="eg-kv">'
        f"<dt>Unsafe actions</dt><dd class='eg-money'>{metrics.unsafe_actions}</dd>"
        f"<dt>Audit chain</dt><dd>{metrics.audit_chain_message}</dd>"
        f"</dl>"
        f'<p class="eg-lede" style="margin-top:12px">No transfer or reversal can '
        f"execute without a single-use, content-bound gate token. Verified by six "
        f"attack classes in <code>tests/integration/test_gate_adversarial.py</code>."
        f"</p></div>"
    )

_html(
    '<div class="eg-foot">'
    "EntitleGraph Close Agent — Razorpay Buildathon 2026, Track 4. "
    "Reference implementation. Synthetic data only. Razorpay test mode only. "
    "No production integration."
    "</div>"
)
