"""Synthetic merchant agreement corpus.

Every document here is FABRICATED for testing. No real merchant, no real terms.

The corpus is written as prose, not as structured terms, because the contract
compiler's whole job is interpretation — handing it pre-structured data would
test nothing. Phrasing deliberately varies (the split is stated from the
platform's side in some agreements and the seller's side in others; holds appear
as words and as digits) so the compiler is not parsing one fixed template.

Four hard situations are planted on purpose (BUILD_PROMPT.md §5.1):

1. **CTR-0003** — mid-cycle rate change, seller share 70% -> 65%, amendment
   executed mid-month but stated as effective from the start of the billing
   month. Two defensible start dates. This is the required "what broke" case.
2. **CTR-0007** — overlapping promotion funding: two clauses each claim a share
   of the same discount and the shares sum to 120%. Unresolvable by arithmetic.
3. **CTR-0004** — delivery-contingent hold where the triggering event may never
   arrive, so entitlement can remain permanently un-arisen rather than late.
4. **CTR-0005** — refund precedence: commission is non-refundable *and* the
   seller payout must be clawed back before the customer is refunded, so the
   ordering of two events determines whether the ledger is correct.
"""

from __future__ import annotations

from datetime import datetime, timezone

from src.common.types import ContractSource

SYNTHETIC_BANNER = (
    "SYNTHETIC DOCUMENT — generated by EntitleGraph for testing purposes.\n"
    "This is not a real merchant agreement and describes no real commercial "
    "relationship."
)


def _utc(date_str: str) -> datetime:
    return datetime.fromisoformat(date_str).replace(tzinfo=timezone.utc)


def _agreement(
    *,
    contract_id: str,
    version: int,
    seller_id: str,
    effective_line: str,
    commission: str,
    settlement: str,
    promotions: str,
    refunds: str,
    tax: str,
    delivery: str,
    preamble: str = "",
) -> str:
    return f"""{SYNTHETIC_BANNER}

MERCHANT AGREEMENT — SCHEDULE B (COMMERCIAL TERMS)

Contract: {contract_id}
Version: {version}
Seller: {seller_id}
{effective_line}
{preamble}
1. COMMISSION. {commission}

2. SETTLEMENT. {settlement}

3. PROMOTIONS. {promotions}

4. REFUNDS. {refunds}

5. TAX. {tax}

6. DELIVERY. {delivery}
"""


def build_contract_sources() -> list[ContractSource]:
    """Return the full synthetic corpus, including the planted hard cases."""
    sources: list[ContractSource] = []

    # -- CTR-0001: plain vanilla, commission stated from the platform side ----
    sources.append(
        ContractSource(
            contract_id="CTR-0001",
            version=1,
            seller_id="SLR-0001",
            effective_from=_utc("2026-01-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0001",
                version=1,
                seller_id="SLR-0001",
                effective_line="Effective from: 2026-01-01",
                commission=(
                    "The Platform shall retain a commission of thirty percent (30%) "
                    "of the Net Order Value, being the amount charged to the customer "
                    "less any promotional discount and less shipping charges."
                ),
                settlement=(
                    "The Seller's share shall become payable only upon confirmation "
                    "of delivery, and shall be settled no earlier than forty-eight "
                    "(48) hours thereafter."
                ),
                promotions=(
                    "Discounts under Platform-run campaigns shall be funded 100% by "
                    "the Platform."
                ),
                refunds=(
                    "Where a customer refund is issued, the Seller payout for that "
                    "order shall first be reversed. Commission retained by the "
                    "Platform is refundable on a pro-rata basis."
                ),
                tax=(
                    "The Platform shall withhold tax at source at one percent (1%) "
                    "of the commission amount."
                ),
                delivery=(
                    "A delivery fee of Rs. 45.00 per confirmed delivery is payable "
                    "to the assigned delivery partner."
                ),
            ),
            notes="Baseline agreement — the clean, unambiguous case.",
        )
    )

    # -- CTR-0002: split stated from the seller's side, no delivery hold -----
    sources.append(
        ContractSource(
            contract_id="CTR-0002",
            version=1,
            seller_id="SLR-0002",
            effective_from=_utc("2026-01-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0002",
                version=1,
                seller_id="SLR-0002",
                effective_line="Effective from: 2026-01-01",
                commission=(
                    "The Seller shall receive seventy-five percent (75%) of the Net "
                    "Order Value. The balance is retained by the Platform as its "
                    "commission."
                ),
                settlement=(
                    "The Seller's share shall be settled on the next settlement cycle "
                    "following payment capture. Delivery confirmation is not a "
                    "precondition to settlement under this agreement."
                ),
                promotions=(
                    "Discounts shall be funded 50% by the Platform and 50% by the "
                    "Seller."
                ),
                refunds=(
                    "Where a customer refund is issued, the Seller payout shall first "
                    "be reversed. Commission is refundable."
                ),
                tax="No tax shall be withheld at source under this agreement.",
                delivery="No delivery partner fee applies to this agreement.",
            ),
            notes="Tests seller-side phrasing and the no-hold settlement path.",
        )
    )

    # -- CTR-0003 v1: the pre-amendment terms --------------------------------
    sources.append(
        ContractSource(
            contract_id="CTR-0003",
            version=1,
            seller_id="SLR-0003",
            effective_from=_utc("2026-01-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0003",
                version=1,
                seller_id="SLR-0003",
                effective_line="Effective from: 2026-01-01",
                commission=(
                    "The Seller shall receive seventy percent (70%) of the Net Order "
                    "Value. The balance is retained by the Platform as its commission."
                ),
                settlement=(
                    "The Seller's share shall become payable upon confirmation of "
                    "delivery, and shall be settled no earlier than twenty-four (24) "
                    "hours thereafter."
                ),
                promotions="Discounts shall be funded 100% by the Platform.",
                refunds=(
                    "Where a customer refund is issued, the Seller payout for that "
                    "order shall first be reversed. Commission is refundable."
                ),
                tax=(
                    "The Platform shall withhold tax at source at one percent (1%) of "
                    "the commission amount."
                ),
                delivery=(
                    "A delivery fee of Rs. 40.00 per confirmed delivery is payable to "
                    "the assigned delivery partner."
                ),
            ),
            notes="Pre-amendment terms for the version-conflict scenario.",
        )
    )

    # -- CTR-0003 v2: THE PLANTED FAILURE -----------------------------------
    # Amendment reduces the seller's share 70% -> 65%. It says it takes effect
    # from the start of the billing month, but it was executed on the 12th.
    # Orders dated 2026-02-01..2026-02-11 therefore have two defensible rates
    # and the resolver must refuse to choose. See docs/CHANGELOG.md.
    sources.append(
        ContractSource(
            contract_id="CTR-0003",
            version=2,
            seller_id="SLR-0003",
            effective_from=_utc("2026-02-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0003",
                version=2,
                seller_id="SLR-0003",
                effective_line=(
                    "This amendment is effective from the commencement of the current "
                    "billing month.\nExecuted on: 2026-02-12"
                ),
                preamble=(
                    "\nAMENDMENT NO. 1 to Schedule B. This amendment supersedes the "
                    "commercial terms of Version 1 in their entirety.\n"
                ),
                commission=(
                    "The Seller shall receive sixty-five percent (65%) of the Net "
                    "Order Value. The balance is retained by the Platform as its "
                    "commission."
                ),
                settlement=(
                    "The Seller's share shall become payable upon confirmation of "
                    "delivery, and shall be settled no earlier than twenty-four (24) "
                    "hours thereafter."
                ),
                promotions="Discounts shall be funded 100% by the Platform.",
                refunds=(
                    "Where a customer refund is issued, the Seller payout for that "
                    "order shall first be reversed. Commission is refundable."
                ),
                tax=(
                    "The Platform shall withhold tax at source at one percent (1%) of "
                    "the commission amount."
                ),
                delivery=(
                    "A delivery fee of Rs. 40.00 per confirmed delivery is payable to "
                    "the assigned delivery partner."
                ),
            ),
            notes=(
                "PLANTED FAILURE CASE: 'commencement of the current billing month' "
                "against a 12 Feb execution date yields two defensible effective "
                "dates (2026-02-01 and 2026-02-12) and nothing in the document ranks "
                "them."
            ),
        )
    )

    # -- CTR-0004: hard case 3 — hold on an event that may never arrive ------
    sources.append(
        ContractSource(
            contract_id="CTR-0004",
            version=1,
            seller_id="SLR-0004",
            effective_from=_utc("2026-01-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0004",
                version=1,
                seller_id="SLR-0004",
                effective_line="Effective from: 2026-01-01",
                commission=(
                    "The Platform shall retain a commission of twenty-five percent "
                    "(25%) of the Net Order Value."
                ),
                settlement=(
                    "No part of the Seller's share shall become payable unless and "
                    "until delivery is confirmed by the assigned delivery partner. "
                    "Settlement shall occur no earlier than seventy-two (72) hours "
                    "after such confirmation."
                ),
                promotions="Discounts shall be funded 100% by the Platform.",
                refunds=(
                    "Where a customer refund is issued, the Seller payout shall first "
                    "be reversed. Commission is refundable."
                ),
                tax=(
                    "The Platform shall withhold tax at source at one percent (1%) of "
                    "the commission amount."
                ),
                delivery=(
                    "A delivery fee of Rs. 45.00 per confirmed delivery is payable to "
                    "the assigned delivery partner."
                ),
            ),
            notes=(
                "HARD CASE: entitlement is contingent on an event that may never "
                "occur. A failed delivery leaves the seller permanently un-entitled, "
                "which is different from being paid late."
            ),
        )
    )

    # -- CTR-0005: hard case 4 — refund precedence + non-refundable commission
    sources.append(
        ContractSource(
            contract_id="CTR-0005",
            version=1,
            seller_id="SLR-0005",
            effective_from=_utc("2026-01-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0005",
                version=1,
                seller_id="SLR-0005",
                effective_line="Effective from: 2026-01-01",
                commission=(
                    "The Platform shall retain a commission of twenty percent (20%) "
                    "of the Gross Order Value, being the list value of the goods "
                    "before any promotional discount."
                ),
                settlement=(
                    "The Seller's share shall become payable upon confirmation of "
                    "delivery. No additional hold period applies."
                ),
                promotions=(
                    "Discounts shall be funded 25% by the Platform and 75% by the "
                    "Seller."
                ),
                refunds=(
                    "The Seller payout for an order shall be reversed prior to any "
                    "refund being issued to the customer. Commission retained by the "
                    "Platform is non-refundable. Reversal shall be completed within "
                    "72 hours."
                ),
                tax=(
                    "The Platform shall withhold tax at source at one percent (1%) of "
                    "the commission amount."
                ),
                delivery="No delivery partner fee applies to this agreement.",
            ),
            notes=(
                "HARD CASE: commission on GROSS (pre-discount) value, non-refundable "
                "commission, and a strict reversal-before-refund ordering rule. Three "
                "interacting clauses where the naive reading is wrong."
            ),
        )
    )

    # -- CTR-0006: mid-size, digits rather than words ------------------------
    sources.append(
        ContractSource(
            contract_id="CTR-0006",
            version=1,
            seller_id="SLR-0006",
            effective_from=_utc("2026-01-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0006",
                version=1,
                seller_id="SLR-0006",
                effective_line="Effective from: 2026-01-01",
                commission=(
                    "The Platform shall retain a commission of 18% of the Net Order "
                    "Value."
                ),
                settlement=(
                    "The Seller's share becomes payable when delivery is confirmed. "
                    "Settlement shall not occur earlier than 24 hours after "
                    "confirmation."
                ),
                promotions="Discounts shall be funded 100% by the Platform.",
                refunds=(
                    "Where a refund is issued the Seller payout shall first be "
                    "reversed. Commission is refundable."
                ),
                tax="No tax shall be withheld at source under this agreement.",
                delivery=(
                    "A delivery fee of Rs. 35.00 per confirmed delivery is payable to "
                    "the assigned delivery partner."
                ),
            ),
            notes="Digit-form terms — checks the compiler is not template-bound.",
        )
    )

    # -- CTR-0007: hard case 2 — overlapping promotion funding ---------------
    sources.append(
        ContractSource(
            contract_id="CTR-0007",
            version=1,
            seller_id="SLR-0007",
            effective_from=_utc("2026-01-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0007",
                version=1,
                seller_id="SLR-0007",
                effective_line="Effective from: 2026-01-01",
                commission=(
                    "The Platform shall retain a commission of twenty-two percent "
                    "(22%) of the Net Order Value."
                ),
                settlement=(
                    "The Seller's share shall become payable upon confirmation of "
                    "delivery, and shall be settled no earlier than 24 hours "
                    "thereafter."
                ),
                promotions=(
                    "Discounts under the Platform's festive campaign shall be funded "
                    "60% by the Platform. Discounts under any seller-elected campaign "
                    "shall be funded 60% by the Seller. Where an order qualifies "
                    "under both campaigns the discount shall be funded under both "
                    "clauses."
                ),
                refunds=(
                    "Where a refund is issued the Seller payout shall first be "
                    "reversed. Commission is refundable."
                ),
                tax=(
                    "The Platform shall withhold tax at source at one percent (1%) of "
                    "the commission amount."
                ),
                delivery=(
                    "A delivery fee of Rs. 45.00 per confirmed delivery is payable to "
                    "the assigned delivery partner."
                ),
            ),
            notes=(
                "HARD CASE: two promotion clauses each claim a share of the same "
                "discount and the shares sum to 120%. Arithmetically unresolvable — "
                "the compiler must refuse rather than normalise."
            ),
        )
    )

    # -- CTR-0008 / 0009 / 0010: further variety -----------------------------
    sources.append(
        ContractSource(
            contract_id="CTR-0008",
            version=1,
            seller_id="SLR-0008",
            effective_from=_utc("2026-01-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0008",
                version=1,
                seller_id="SLR-0008",
                effective_line="Effective from: 2026-01-01",
                commission=(
                    "The Seller shall receive eighty percent (80%) of the Net Order "
                    "Value; the balance is the Platform's commission."
                ),
                settlement=(
                    "The Seller's share shall become payable upon confirmation of "
                    "delivery with no further hold."
                ),
                promotions="Discounts shall be funded 100% by the Seller.",
                refunds=(
                    "Where a refund is issued the Seller payout shall first be "
                    "reversed. Commission is refundable."
                ),
                tax=(
                    "The Platform shall withhold tax at source at one percent (1%) of "
                    "the commission amount."
                ),
                delivery=(
                    "A delivery fee of Rs. 45.00 per confirmed delivery is payable to "
                    "the assigned delivery partner."
                ),
            ),
            notes="Seller-funded promotions — inverts the usual funding direction.",
        )
    )

    sources.append(
        ContractSource(
            contract_id="CTR-0009",
            version=1,
            seller_id="SLR-0009",
            effective_from=_utc("2026-01-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0009",
                version=1,
                seller_id="SLR-0009",
                effective_line="Effective from: 2026-01-01",
                commission=(
                    "The Platform shall retain a commission of thirty-five percent "
                    "(35%) of the Net Order Value."
                ),
                settlement=(
                    "The Seller's share shall become payable upon confirmation of "
                    "delivery and shall be settled no earlier than forty-eight (48) "
                    "hours thereafter."
                ),
                promotions=(
                    "Discounts shall be funded 50% by the Platform and 50% by the "
                    "Seller."
                ),
                refunds=(
                    "Where a refund is issued the Seller payout shall first be "
                    "reversed. Commission is refundable."
                ),
                tax=(
                    "The Platform shall withhold tax at source at one percent (1%) of "
                    "the commission amount."
                ),
                delivery=(
                    "A delivery fee of Rs. 40.00 per confirmed delivery is payable to "
                    "the assigned delivery partner."
                ),
            ),
            notes="High-commission agreement with a 48h hold.",
        )
    )

    sources.append(
        ContractSource(
            contract_id="CTR-0010",
            version=1,
            seller_id="SLR-0010",
            effective_from=_utc("2026-01-01"),
            effective_to=None,
            body=_agreement(
                contract_id="CTR-0010",
                version=1,
                seller_id="SLR-0010",
                effective_line="Effective from: 2026-01-01",
                commission=(
                    "The Platform shall retain a commission of twenty-eight percent "
                    "(28%) of the Net Order Value."
                ),
                settlement=(
                    "The Seller's share shall be settled following payment capture. "
                    "Delivery confirmation is not a precondition to settlement."
                ),
                promotions="Discounts shall be funded 100% by the Platform.",
                refunds=(
                    "Where a refund is issued the Seller payout shall first be "
                    "reversed. Commission is refundable."
                ),
                tax=(
                    "The Platform shall withhold tax at source at one percent (1%) of "
                    "the commission amount."
                ),
                delivery="No delivery partner fee applies to this agreement.",
            ),
            notes="No-hold settlement, platform-funded promotions.",
        )
    )

    return sources


# ---------------------------------------------------------------------------
# Intended terms — the ground truth the prose above is *meant* to express.
# ---------------------------------------------------------------------------
# These are what a careful human reader should extract from each agreement. Two
# things depend on them:
#
# 1. ``tests/unit/test_compiler_fidelity.py`` asserts the compiler recovers
#    exactly these values from the prose. That is the real test of the
#    compiler — not that it produces *a* policy, but that it produces the
#    *right* one.
# 2. The ledger generator settles orders from this table rather than from the
#    compiled policy, so the synthetic ledger is built independently of the
#    module being evaluated. If the compiler misreads a clause, the engine's
#    output diverges from the ledger and the evaluation harness reports it,
#    instead of both sides sharing one mistake and agreeing.
#
# CTR-0007 has no entry: it is deliberately unresolvable, so there is no correct
# set of terms to recover.
INTENDED_TERMS: dict[tuple[str, int], dict] = {
    ("CTR-0001", 1): dict(
        commission_bps=3000, applies_to="order_net", requires_delivery=True,
        hold_hours=48, promo_platform_bps=10000, promo_seller_bps=0,
        commission_refundable=True, reversal_first=True, tds_bps=100,
        delivery_fee_paise=4500,
    ),
    ("CTR-0002", 1): dict(
        commission_bps=2500, applies_to="order_net", requires_delivery=False,
        hold_hours=0, promo_platform_bps=5000, promo_seller_bps=5000,
        commission_refundable=True, reversal_first=True, tds_bps=0,
        delivery_fee_paise=0,
    ),
    ("CTR-0003", 1): dict(
        commission_bps=3000, applies_to="order_net", requires_delivery=True,
        hold_hours=24, promo_platform_bps=10000, promo_seller_bps=0,
        commission_refundable=True, reversal_first=True, tds_bps=100,
        delivery_fee_paise=4000,
    ),
    ("CTR-0003", 2): dict(
        commission_bps=3500, applies_to="order_net", requires_delivery=True,
        hold_hours=24, promo_platform_bps=10000, promo_seller_bps=0,
        commission_refundable=True, reversal_first=True, tds_bps=100,
        delivery_fee_paise=4000,
    ),
    ("CTR-0004", 1): dict(
        commission_bps=2500, applies_to="order_net", requires_delivery=True,
        hold_hours=72, promo_platform_bps=10000, promo_seller_bps=0,
        commission_refundable=True, reversal_first=True, tds_bps=100,
        delivery_fee_paise=4500,
    ),
    ("CTR-0005", 1): dict(
        commission_bps=2000, applies_to="order_gross", requires_delivery=True,
        hold_hours=0, promo_platform_bps=2500, promo_seller_bps=7500,
        commission_refundable=False, reversal_first=True, tds_bps=100,
        delivery_fee_paise=0,
    ),
    ("CTR-0006", 1): dict(
        commission_bps=1800, applies_to="order_net", requires_delivery=True,
        hold_hours=24, promo_platform_bps=10000, promo_seller_bps=0,
        commission_refundable=True, reversal_first=True, tds_bps=0,
        delivery_fee_paise=3500,
    ),
    ("CTR-0008", 1): dict(
        commission_bps=2000, applies_to="order_net", requires_delivery=True,
        hold_hours=0, promo_platform_bps=0, promo_seller_bps=10000,
        commission_refundable=True, reversal_first=True, tds_bps=100,
        delivery_fee_paise=4500,
    ),
    ("CTR-0009", 1): dict(
        commission_bps=3500, applies_to="order_net", requires_delivery=True,
        hold_hours=48, promo_platform_bps=5000, promo_seller_bps=5000,
        commission_refundable=True, reversal_first=True, tds_bps=100,
        delivery_fee_paise=4000,
    ),
    ("CTR-0010", 1): dict(
        commission_bps=2800, applies_to="order_net", requires_delivery=False,
        hold_hours=0, promo_platform_bps=10000, promo_seller_bps=0,
        commission_refundable=True, reversal_first=True, tds_bps=100,
        delivery_fee_paise=0,
    ),
}

# Contracts whose compiled policy is deliberately un-computable. The evaluation
# harness asserts these produce blocking ambiguities rather than numbers.
DELIBERATELY_AMBIGUOUS = {"CTR-0007"}

# The order window in which CTR-0003's two versions both defensibly apply.
VERSION_CONFLICT_WINDOW = (_utc("2026-02-01"), _utc("2026-02-12"))
